FROM locustio/locust
WORKDIR /tests
COPY tests/requirements.txt /tests/
COPY /tests/*.py /tests/
RUN pip3 install --no-cache --upgrade pip -r /tests/requirements.txt
ENTRYPOINT ["locust", "--locustfile", "/tests/locustfile.py", "--master", "-H http://locust:8089"]