START TRANSACTION;

DO $$
BEGIN
    INSERT INTO "Dogs" ("Fact") VALUES ('All dogs can be traced back 40 million years ago to a weasel animal called the Miacis which dwelled in trees and dens. The Miacis later evolved into the Tomarctus, a direct forbear of the genus Canis, which includes the wolf and jackal as well as the dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Ancient Egyptians revered their dogs. When a pet dog would die, the owners shaved off their eyebrows, smeared mud in their hair, and mourned aloud for days.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Small quantities of grapes and raisins can cause renal failure in dogs. Chocolate, macadamia nuts, cooked onions, or anything with caffeine can also be harmful.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Apple and pear seeds contain arsenic, which may be deadly to dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Rock star Ozzy Osborne saved his wife Sharons Pomeranian from a coyote by tackling ad wresting the coyote until it released the dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In 2003, Dr. Roger Mugford invented the "wagometer", a device that claims to interpret a dogs exact mood by measuring the wag of its tail.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs shoulder blades are unattached to the rest of the skeleton to allow greater flexibility for running.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies are sometimes rejected by their mother if they are born by cesarean and cleaned up before being given back to her.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The phrase "raining cats and dogs" originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('During the Middle Ages, Great Danes and Mastiffs were sometimes suited with armor and spiked collars to enter a battle or to defend supply caravans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Pekingese and Japanese Chins were so important in the ancient Far East that they had their own servants and were carried around trade routes as gifts for kings and emperors. Pekingese were even worshipped in the temples of China for centuries.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The shape of a dogs face suggests how long it will live. Dogs with sharp, pointed faces typically live longer. Dogs with very flat faces, such as bulldogs, often have shorter lives.');
    INSERT INTO "Dogs" ("Fact") VALUES ('After the fall of Rome, human survival often became more important than breeding and training dogs. Legends of werewolves emerged during this time as abandoned dogs traveling in packs commonly roamed streets and terrified villagers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('During the Middle Ages, mixed breeds of peasants dogs were required to wear blocks around their necks to keep them from breeding with noble hunting dogs. Purebred dogs were very expensive and hunting became the province of the rich.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The most dogs ever owned by one person were 5,000 Mastiffs owned by Kublai Khan.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The American Kennel Club, the most influential dog club in the United States, was founded in 1884.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The most popular male dog names are Max and Jake. The most popular female dog names are Maggie and Molly.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Scholars have argued over the metaphysical interpretation of Dorothys pooch, Toto, in the Wizard of Oz. One theory postulates that Toto represents Anubis, the dog-headed Egyptian god of death, because Toto consistently keeps Dorothy from safely returning home.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Weird dog laws include allowing police offers in Palding, Ohio, to bite a dog to quiet it. In Ventura County, California, cats and dogs are not allowed to have sex without a permit.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The first dog chapel was established in 2001. It was built in St. Johnsbury, Vermont, by Stephan Huneck, a childrens book author whose five dogs helped him recuperate from a serious illness.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Those born under the sign of the dog in Chinese astrology are considered to be loyal and discreet, though slightly temperamental.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In Iran, it is against the law to own a dog as a pet. However, if an owner can prove the dog is a guard or hunting dog, this restriction doesnt apply. Muslim reticence concerning dogs is perhaps due to the fact that rabies has always been endemic in the Middle East.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The ancient Mbaya Indians of the Gran Chaco in South America believed that humans originally lived underground until dogs dug them up.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Plato once said that "a dog has the soul of a philosopher".');
    INSERT INTO "Dogs" ("Fact") VALUES ('French poodles did not originate in France but in Germany "poodle" comes from the German pudel or pudelhund, meaning "splashing dog". Some scholars speculate the poodles puffs of hair evolved when hunters shaved the poodle for more efficient swimming, while leaving the pom-poms around the major joints to keep them warm.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The name of the dog on the Cracker Jacks box is Bingo. The Taco Bell Chihuahua is a rescued dog named Gidget.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The first dogs were self-domesticated wolves which, at least 12,000 years ago, became attracted to the first sites of permanent human habitation.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dachshunds were bred to fight badgers in their dens.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Laika, a Russian stray, was the first living mammal to orbit the Earth, in the Soviet Sputnik spacecraft in 1957. Though she died in space, her daughter Pushnika had four puppies with President John F. Kennedys terrier, Charlie.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dalmatians are completely white at birth.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The term "dog days of summer" was coined by the ancient Greeks and Romans to describe the hottest days of summer that coincided with the rising of the Dog Star, Sirius.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Alexander the Great is said to have founded and named a city Peritas, in memory of his dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In ancient Greece, kennels of dogs were kept at the sanctuary of Asclepius at Epidaurus. Dogs were frequently sacrificed there because they were plentiful, inexpensive, and easy to control. During the July 25 celebration of the kunophontis "the massacre of dogs", dog sacrifices were performed to appease the ancestors of Apollos son, Linos, who was devoured by dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dog trainers in ancient China were held in high esteem. A great deal of dog domestication also took place in China, especially dwarfing and miniaturization.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The ancient religion Zoroastrianism includes in its religious text titled the Zend Avesta a section devoted to the care and breeding of dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The earliest European images of dogs are found in cave paintings dating back 12,000 years ago in Spain.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The dog was frequently depicted in Greek art, including Cerberus, the three-headed hound guarding the entrance to the underworld, and the hunting dogs which accompanied the virgin goddess of the chase, Diana.');
    INSERT INTO "Dogs" ("Fact") VALUES ('During the Renaissance, detailed portraits of the dog as a symbol of fidelity and loyalty appeared in mythological, allegorical, and religious art throughout Europe, including works by Leonardo da Vinci, Diego Vel\u00e1zquez, Jan van Eyck, and Albrecht Durer.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A puppy is born blind, deaf, and toothless.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Basenji is the worlds only barkless dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dog interprets a smiling person as baring their teeth, which is an act of aggression.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The origin of amputating a dogs tail may go back to the Roman writer Lucius Columellas "A.D. 4-70" assertion that tail docking prevented rabies.');
    INSERT INTO "Dogs" ("Fact") VALUES ('One of Shakespeares most mischievous characters is Crab, the dog belonging to Launce in the Two Gentlemen of Verona. The word "watchdog" is first found in The Tempest.');
    INSERT INTO "Dogs" ("Fact") VALUES ('President Franklin Roosevelt created a minor international incident when he claimed he sent a destroyer to the Aleutian Islands just to pick up his Scottish Terrier, Fala, who had been left behind.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Within hours of the September 11, 2001, attack on the World Trade Center, specially trained dogs were on the scene, including German Shepherds, Labs, and even a few little Dachshunds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('It costs approximately $10,000 to train a federally certified search and rescue dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The smallest dog on record was a matchbox-size Yorkshire Terrier. It was 2.5 inches tall at the shoulder, 3.5 inches from nose tip to tail, and weighed only 4 ounces.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Hollywoods first and arguably best canine superstar was Rin Tin Tin, a five-day-old German Shepherd found wounded in battle in WWI France and adopted by an American soldier, Lee Duncan. He would sign his own contracts with his paw print.');
    INSERT INTO "Dogs" ("Fact") VALUES ('At the end of WWI, the German government trained the first guide dogs for war-blinded soldiers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dog can locate the source of a sound in 1/600 of a second and can hear sounds four times farther away than a human can.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Touch is the first sense the dog develops. The entire body, including the paws, is covered with touch-sensitive nerve endings.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Eighteen muscles or more can move a dogs ear.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The names of 77 ancient Egyptian dogs have been recorded. The names refer to color and character, such as Blackie, Ebony, Good Herdsman, Reliable, and Brave One.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In Egypt, a person bitten by a rabid dog was encouraged to eat the roasted liver of a dog infected with rabies to avoid contracting the disease. The tooth of a dog infected with rabies would also be put in a band tied to the arm of the person bitten. The menstrual blood of a female dog was used for hair removal, while dog genitals were used for preventing the whitening of hair.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In early Christian tradition, Saint Christopher, the patron saint of travelers, is sometimes depicted with a dogs head.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The oldest known dog bones were found in Asia and date as far back as 10,000 B.C. The first identifiable dog breed appeared about 9000 B.C. and was probably a type of Greyhound dog used for hunting.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There are an estimated 400 million dogs in the world.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The U.S. has the highest dog population in the world. France has the second highest.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dog nose prints are as unique as human finger prints and can be used to identify them.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Bloodhound dogs have a keen sense of smell and have been used since the Middle Ages to track criminals.');
    INSERT INTO "Dogs" ("Fact") VALUES ('It is much easier for dogs to learn spoken commands if they are given in conjunction with hand signals or gestures.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs in a pack chase and hunt than a single dog on its own. Two dogs are enough to form a pack.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can see in color, though they see colors similar to a color-blind human. They can see better when the light is low.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Petting dogs is proven to lower blood pressure of dog owners.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have lived with humans for over 14,000 years. Cats have lived with people for only 7,000 years.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Zorba, an English mastiff, is the biggest dog ever recorded. He weighed 343 pounds and measured 8 feet 3 inches from his nose to his tail.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The average dog can run about 19 mph. Greyhounds are the fastest dogs on Earth and can run at speeds of 45 mph.');
    INSERT INTO "Dogs" ("Fact") VALUES ('One female dog and her female children could produce 4,372 puppies in seven years.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The most popular dog breed in Canada, U.S., and Great Britain is the Labrador retriever.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Greyhounds appear to be the most ancient dog breed. "Greyhound" comes from a mistake in translating the early German name Greishund, which means "old" or "ancient dog" not from the color gray.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The oldest dog on record was an Australian cattle dog named Bluey who lived 29 years and 5 months. In human years, that is more than 160 years old.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Most experts believe humans domesticated dogs before donkeys, horses, sheep, goats, cattle, cats, or chickens.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A person standing still 300 yards away is almost invisible to a dog. But a dog can easily identify its owner standing a mile away if the owner is waving his arms.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs with big, square heads and large ears "the Saint Bernard" are the best at hearing subsonic sounds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can smell about 1,000 times better than humans. While humans have 5 million smell-detecting cells, dogs have more than 220 million. The part of the brain that interprets smell is also four times larger in dogs than in humans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Some dogs can smell dead bodies under water, where termites are hiding, and natural gas buried under 40 feet of dirt. They can even detect cancer that is too small to be detected by a doctor and can find lung cancer by sniffing a persons breath.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have a wet nose to collect more of the tiny droplets of smelling chemicals in the air.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs love sweets a lot more than cats do. While cats have around only 473 taste buds, dogs have about 1,700 taste buds. Humans have approximately 9,000.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Different smells in the a dogs urine can tell other dogs whether the dog leaving the message is female or male, old or young, sick or healthy, happy or angry.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In Croatia, scientists discovered that lampposts were falling down because a chemical in the urine of male dogs was rotting the metal.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are about as smart as a two- or three-year-old child. This means they can understand about 150-200 words, including signals and hand movements with the same meaning as words.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Countess Karlotta Libenstein of Germany left approximately $106 million to her Alsatin, Gunther III, when she died in 1992.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A lost Dachshund was found swallowed whole in the stomach of a giant catfish in Berlin on July 2003.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In Australia, a man who was arrested for drug possession argued his civil rights were violated when the drug-sniffing dog nuzzled his crotch. While the judge dismissed the charges, they were later reinstated when a prosecutor pointed out that in the animal kingdom, crotch nuzzling was a friendly gesture.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Beagle came into prominence in the 1300s and 1400s during the days of King Henry VII of England. Elizabeth I was fond of Pocket Beagles, which were only 9 inches high.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The best dog to reportedly attract a date is the Golden Retriever. The worst is the Pit Bull.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Akita is one of the most challenging dogs to own. Some insurance companies have even characterized it as the #1 "bad dog" and may even raise an Akita owners homeowner insurance costs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Beagle and Collie are the nosiest dogs, while the Akbash Dog and the Basenji are the quietest.');
    INSERT INTO "Dogs" ("Fact") VALUES ('One survey reports that 33 of dog owners admit they talk to their dogs on the phone or leave messages on answering machines while they are away.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Thirty percent of all Dalmatians are deaf in one or both ears. Because bulldogs have extremely short muzzles, many spend their lives fighting suffocation. Because Chihuahuas have such small skulls, the flow of spinal fluid can be restricted, causing hydrocephalus, a swelling of the brain.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The grief suffered after a pet dog dies can be the same as that experienced after the death of a person.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There are almost 5 million dog bites per year; children are the main victims. Dog bites cause losses of over $1 billion a year.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A person should never kick a dog facing him or her. Some dogs can bite 10 times before a human can respond.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The most intelligent dogs are reportedly the Border Collie and the Poodle, while the least intelligent dogs are the Afghan Hound and the Basenji.');
    INSERT INTO "Dogs" ("Fact") VALUES ('One kind of Pekingese is referred to as a "sleeve" because it was bred to fit into a Chinese empress sleeves, which was how it was often carried around.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Is it a duck or a dog? The Newfoundland breed has a water resistant coat and webbed feet. This dog was originally bred to help haul nets for fishermen and rescuing people at risk of drowning.');
    INSERT INTO "Dogs" ("Fact") VALUES ('It pays to be a lap dog. Three dogs "from First Class cabins!" survived the sinking of the Titanic two Pomeranians and one Pekingese.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A Beatles hit. Its rumored that, at the end of the Beatles song, "A Day in the Life" Paul McCartney recorded an ultrasonic whistle, audible only to dogs, just for his Shetland sheepdog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Wow, check out those choppers! Puppies have 28 teeth and normal adult dogs have 42.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Chase that tail! Dogs chase their tails for a variety of reasons: curiosity, exercise, anxiety, predatory instinct or, they might have fleas! If your dog is chasing his tail excessively, talk with your vet.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Seeing spots? Or not! Dalmatian puppies are pure white when they are born and develop their spots as they grow older.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs do dream! Dogs and humans have the same type of slow wave sleep "SWS" and rapid eye movement "REM" and during this REM stage dogs can dream. The twitching and paw movements that occur during their sleep are signs that your pet is dreaming.');
    INSERT INTO "Dogs" ("Fact") VALUES ('No night vision goggles needed! Dogs eyes contain a special membrane, called the tapetum lucidum, which allows them to see in the dark.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Pitter patter. A large breed dogs resting heart beats between 60 and 100 times per minute, and a small dog breeds heart beats between 100-140. Comparatively, a resting human heart beats 60-100 times per minute.');
    INSERT INTO "Dogs" ("Fact") VALUES ('If your dogs acting funny, get out the umbrella! According to a Petside.com/Associated Press poll, 72 of dog owners believe their dog can detect when stormy weather is on the way.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Its not a fever! A dogs normal temperature is between 101 and 102.5 degrees Fahrenheit or between 38 and 39 degress Celsius');
    INSERT INTO "Dogs" ("Fact") VALUES ('Is something wet? Humans sweat everywhere, dogs only sweat through the pads of their feet.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Heres looking at you. Dogs have three eyelids, an upper lid, a lower lid and the third lid, called a nictitating membrane or "haw" which helps keep the eye moist and protected.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Americans love dogs! 44 of U.S. households have a dog, which equates to 55.3 million homes.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Move over Rover! 45 of dogs sleep in their owners bed!');
    INSERT INTO "Dogs" ("Fact") VALUES ('Why are dogs noses so wet? Dogs noses secrete a thin layer of mucous that helps them absorb scent. They then lick their noses to sample the scent through their mouth.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Yummy! Dogs have about 1,700 taste buds. Humans have approximately 9,000 and cats have around 473.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Watch that plate of cookies! A Dogs sense of smell is 10,000 100,000 times more acute as that of humans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Its not so black and white. Its a myth that dogs only see in black and white. In fact, its believed that dogs see primarily in blue, greenish-yellow, yellow and various shades of gray.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Did you hear that? Sound frequency is measured in Hertz "Hz". The higher the Hertz, the higher-pitched the sound. Dogs hear best at 8,000 Hz, while humans hear best at around 2,000 Hz.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Express yourself. Dogs ears are extremely expressive. Its no wonder! There are more than a dozen separate muscles that control a dogs ear movements.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Growing up. While the Chow Chow dogs are well known for their distinctive blue-black tongues, theyre actually born with pink tongues. They turn blue-black at 8-10 weeks of age.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Why do they do that? When dogs kick after going to the bathroom, they are using the scent glands on their paws to further mark their territory.');
    INSERT INTO "Dogs" ("Fact") VALUES ('No, its not just to make themselves look adorable. Dogs curl up in a ball when they sleep due to an age-old instinct to keep themselves warm and protect their abdomen and vital organs from predators.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are capable of understanding up to 250 words and gestures, can count up to five and can perform simple mathematical calculations. The average dog is as intelligent as a two-year-old child.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Some stray Russian dogs have figured out how to use the subway system in order to travel to more populated areas in search of food.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs dont enjoy being hugged as much as humans and other primates. Canines interpret putting a limb over another animal as a sign of dominance.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Two stray dogs in Afghanistan saved 50 American soliders. A Facebook group raised $21,000 to bring the dogs back to the US and reunite them with the soldiers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('This pup, Nesbit, earned over one million Delta airline miles in his life and had his own frequent flier card.');
    INSERT INTO "Dogs" ("Fact") VALUES ('One of Michael Vicks former fighting dogs, Leo, went on to be a therapy dog who comforted dying children.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Service dogs are trained to know when they are on duty. When their harness is on, they know its business time. When you take it off, the pups immediately become playful and energetic.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Tiger Woods stuttered as a child and used to talk to his dog until he fell asleep in an effort to get rid of it.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Seeing eye dogs pee and poo on command so that their owners can clean up after them. The command is usually "Get busy!" and pups will pace back and forth until they do their business. Male dogs are also trained to do their business without lifting their leg.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In ancient China, an emperors last line of defense was a small Pekingese dog literally hidden up his sleeve.');
    INSERT INTO "Dogs" ("Fact") VALUES ('When Lord Byron was informed that his dog was not allowed to come with him to Cambridge Trinity College, he retaliated by bringing a bear instead.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In 1860s San Francisco, two stray dogs who were best friends became local celebrities. Their exploits were celebrated in local papers and they were granted immunity from the citys dog catchers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There is a dog-shaped building in New Zealand.');
    INSERT INTO "Dogs" ("Fact") VALUES ('This dog, Nakio, lost all of his legs to frostbite in Colorado, but now has four prosthetic legs and can run around normally.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The wetness of a dogs nose is essential for determining what direction a smell is coming from.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Hyenas arent actually dogs. They are more closely related to cats.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Spiked dog collars were invented in ancient Greece and were originally designed to protect dogs throats from wolf attacks.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Baks the blind boxer has a seeing eye goose named Buttons. Buttons the four-year-old goose leads her pup around everywhere either by hanging onto him with her neck, or by honking to tell him which way to go.');
    INSERT INTO "Dogs" ("Fact") VALUES ('"Frito Feet" is the name of the phenomenon in which the bacteria on a dogs paws cause them to smell similar to corn chips. Because a pups feet are in constant contact with the ground, they pick up tons of microorganisms in their paws. When dogs cool off by sweating through the pads of their feet, the combo of moisture and bacteria releaces a nutty, popcorn aroma. Basically its dog B.O.');
    INSERT INTO "Dogs" ("Fact") VALUES ('It is a myth that dogs are color blind. They can actually see in color, just not as vividly as humans. It is akin to our vision at dusk.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs DO have better low-light vision than humans because of a special light-reflecting layer behind their retinas.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A German Shepherd guide dog led her blind companion the entire 2,100 mile Appalachian Trail.');
    INSERT INTO "Dogs" ("Fact") VALUES ('If never spayed or neutered, a female dog, her mate, and their puppies could produce over 66,000 dogs in 6 years!');
    INSERT INTO "Dogs" ("Fact") VALUES ('Chihuahuas are born with a soft spot in their skull which closes with age.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The breed Lundehune has 6 toes and can close its ears.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Teddy Roosevelts dog, Pete, ripped a French ambassadors pants off at the White House.');
    INSERT INTO "Dogs" ("Fact") VALUES ('President Lyndon Johnson had two beagles named Him and Her.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Franklin Roosevelt spent $15,000 for a destroyer to pick up his Scottie in the Aleutian Islands.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In Roman times, mastiffs donned light armor and were sent after mounted knights.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Russians trained dogs during WWII to run suicide missions with mines strapped to their backs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs mouth exerts 15200 pounds of pressure per square inch with some dogs exerting up to 450 pounds per square inch.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A one year old dog is as physically mature as a 15 year old human.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The U.S. has the highest dog population in the world.');
    INSERT INTO "Dogs" ("Fact") VALUES ('France has the 2nd highest dog population.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The average city dog lives 3 years longer than a country dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Eighty-seven percent of dog owners say their dog curls up beside them or at their feet while they watch T.V.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can be trained to detect epileptic seizures in humans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Fifteen people die in the U.S. every year from dog bites.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In 2002 alone, more people in the U.S. were killed by dogs than by sharks in the past 100 years.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Gidget is the name of the Taco Bell dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Basset Hounds cannot swim.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Greyhounds are the fastest dogs on earth, with speeds of up to 45 miles per hour.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The bible mentions dogs 14 times.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Obesity is the #1 health problem among dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('An estimated 1,000,000 dogs in the U.S. have been named as the primary beneficiaries in their owners will.');
    INSERT INTO "Dogs" ("Fact") VALUES ('An American Animal Hospital Association poll found that 33 of dog owners admit to talking to their dogs on the phone and leaving answering machine messages for them while away.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs nose prints are as unique as a humans finger prints, and can be used to accurately identify them.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Seventy percent of people sign their pets name on greeting and holiday cards.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Fifty-eight percent of people put pets in family and holiday portraits.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There are only 350 Cisky Terriers in the world, possibly making it the rarest breed.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have no sense of time.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Humans have kept dogs as pets for over 12,000 years.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The largest breed of dog is the Irish Wolfhound.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The worlds smallest dog breed is the Chihuahua.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The St. Bernard is the heaviest dog breed.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Only dogs and humans have prostates.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs do not have an appendix.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The oldest known breed is the Saluki, originally trained by Egyptians to help them track game.');
    INSERT INTO "Dogs" ("Fact") VALUES ('An African wolf dog known as the Basenji is the only dog in the world that cannot bark.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There are 703 breeds of purebred dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dachshunds were originally bred for fighting badgers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The worlds smartest dogs are thought to be "1" the Border Collie, "2" the Poodle, and "3" the Golden Retriever and the dumbest dog is believed to be the Afghan Hound.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs sense of smell is more than 100,000 times stronger than that of a human.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs need a strong sense of smell because their eyesight is not as keen as a humans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs judge objects first by their movement, then by their brightness, and lastly by their shape.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Chocolate contains a substance known as theobromine similar to caffeine which can kill dogs or, at the very least, make them violently ill.');
    INSERT INTO "Dogs" ("Fact") VALUES ('George Washington had 36 dogall Foxhoundwith one named Sweetlips.');
    INSERT INTO "Dogs" ("Fact") VALUES ('All dogs are identical in anatomy, with 321 bones and 42 permanent teeth.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Smaller breeds mature faster than larger breeds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Female dogs are only ready to mate in heat twice a year for a total of roughly 20 days.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies sleep 90% of the day for their first few weeks.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Toto in The Wizard of Oz was played by a female Cairn Terrier named Terry.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs vision is not fully developed until after the first month.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have twice as many muscles to move their ears as people.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The longer a dogs nose, the more effective its internal cooling system.');
    INSERT INTO "Dogs" ("Fact") VALUES ('An elderly woman was saved by her 12-pound Yorkshire Terrier, who fought off an 80- pound Akita, and survived with only 9 stitches.');
    INSERT INTO "Dogs" ("Fact") VALUES ('U.S. Customs dogs "Rocky" and "Barco" were so good at patrolling the border that Mexican drug lords put a $300,000 bounty on their heads.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are all direct descendants of wolves.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Wolves and dogs can mate to produce fertile offspring.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Female wolves have been known to travel great distances to regurgitate full meals for their hungry pups.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Cerberus was the tri-headed dog that guarded the underworld in Greek mythology.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs pregnancy lasts for approximately 60 days.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Humans can detect sounds at 20,000 times per second, while dogs can sense frequencies of 30,000 times per second.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The earliest dog fossil dates back to nearly 10,000 B.C.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Bloodhounds are prized for their ability to single out and identify a number of scents simultaneously.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The ancient Chinese carried Pekingese puppies in the sleeves of their robes.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Boxers are so named because of their manner of playing using their front paws.');
    INSERT INTO "Dogs" ("Fact") VALUES ('All breeds of dog have been found to attack livestock, from 3-month-old puppies to 13-year-old poodles.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs heart beats up to 120 times per minute, or 50 faster than the average human heartbeat of 80 times per minute');
    INSERT INTO "Dogs" ("Fact") VALUES ('The oldest dog on record a Queensland Heeler named Bluey was 29 years, 5 months old.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Davy Crockett had a dog named Sport.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs were first domesticated by cavemen.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs live an average of 15 years.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Many foot disorders in dogs are simply an issue of too-long toenails.');
    INSERT INTO "Dogs" ("Fact") VALUES ('More than 5,000,000 puppies are born in the U.S. every year.');
    INSERT INTO "Dogs" ("Fact") VALUES ('More than 1 in 3 American families own a dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Girl Scouts and Boy Scouts both offer merit badges in dog care.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are natural pack animals.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are naturally submissive to any creature with higher pack status, human or canine.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs with little human contact in the first three months typically dont make good pets.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Chihuahua was named after the state in Mexico where they were discovered.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The largest dog was an English Mastiff who weighed 343 pounds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In 2001, it was estimated that there are approximately 400 million dogs in the world.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In Old England, the word "hound" was used to refer to all types of dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The process of birthing puppies is called "whelping".');
    INSERT INTO "Dogs" ("Fact") VALUES ('The famous nickname "mans best friend" is used in many other languages as well as English.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs dont see in black-and-white, they have 2 color receptors, and can see yellow and blue.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs definitely dont see hawks. They have very poor eyesight, but can distinguish movement 10-20 times better than humans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Even with their poor eyesight, dogs can still see better at night than humans do.');
    INSERT INTO "Dogs" ("Fact") VALUES ('While not the best when it comes to sight, dogs have a keen sense of hearing, and can hear sounds at 4 times the distance of humans.');
    INSERT INTO "Dogs" ("Fact") VALUES ('At the age of 4 weeks, most dogs have developed the majority of their vocalizations.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Most dogs are capable of understanding up to 250 words and gestures.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A Border Collie named Chaser has learned the names of 1,022 toys, and can retrieve each by name.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can count up to five and can perform simple mathematical calculations.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Its been demonstrated that dogs can reduce both physical and emotional anxiety.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have been used since the 1700s for therapy.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs with a flesh colored nose is said to have a "Dudley Nose".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Pugs and other dogs with short muzzles have a peculiar head-type known as "Brachycephalic".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Hound dogs and long-nosed dogs also have a unique name for their head-type: "Dolichocephalic".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs sleep for an average of 10 hours per day.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs engage in rapid-eye-movement when they sleep, and have dreams.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The World Canine Organization recognizes 339 breeds of dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Analysis of the dog genome demonstrate only 4 major types of dogs: "Old Lineage Dogs", "Mastiff-type Dogs", "Herding Dogs" and "Modern Hunting Dogs".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are not exclusively carnivores: they can adapt to different foods, and a percentage of their diets can be fruits and vegetables.');
    INSERT INTO "Dogs" ("Fact") VALUES ('he French Bulldog is incapable of reproducing naturally.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In addition to "formal" forms of dog training (operant conditioning, reinforcement, or classical conditioning), dogs are able to learn merely from observation.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Saint Bernard gains its name from the "Great St. Bernard Hospice" the monastery where Barry and other mountain dogs was raised by monks to rescue victims from the snowy Alps.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A Great Dane named "Just Nuisance" is the only dog to have officially enlisted in the Royal Navy.');
    INSERT INTO "Dogs" ("Fact") VALUES ('When "Bobbie" a Collie/Shepherd mix, was accidentally abandoned on a family vacation, he traveled 2,551 miles over six months to return to his home.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There are 4 constellations named after dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Golden Retriever, one of the most popular dog breeds, was first bred in Scotland in the mid 1800s.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A couple presidential dogs were Golden Retrievers: "Liberty" the presidential dog of Gerald Ford, and "Victory" Ronald Reagans dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Flyball, a dog sport consisting of relays, hurdles, and ball retrieving, was developed in the late 60s, and the first tournament was held in 1983.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The current world record for a Flyball race is 14.413 seconds, set by the team "Touch N Go" of Las Vegas.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Labrador Retriever has been the most popular dog breed since 1991.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Labrador is so popular, in 2006 there were approximately 3-5 times more Labs as there were German Shepherds or Golden Retrievers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('One of the most famous Labrador Retrievers was "Endal" an assistance dog recognized as the most decorated dog in the world.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Endal was the first dog to ride on the London Eye (the characteristic ferris wheel in London, England), and was also the first known dog to successfully use a ATM machine.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Two Labradors, Lucky and Flo, were the first dogs known for sniffing out pirated DVDs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Search and Rescue dog training begin as games played while puppies.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Some Search and Rescue (SaR) Dogs are trained to sniff out humans 1/4 mile away or more.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs powerful sense of smell is frequently called upon to detect anything from mines and explosives to termites and bed bugs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Conservationists have used dogs to find bumblebee hives in order to protect endangered species.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies love games such as hide and seek! Hide, then call your pups name so she can try to find you.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can learn more than 1000 words.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Big happy "helicopter" tail wagging is one sign of a really nice dog');
    INSERT INTO "Dogs" ("Fact") VALUES ('Upright, stiff, rapid tail movement is not wagging or "friendly" but indicates a dog whos rather excited and focused.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies grow to half their body weight in the first four to five months!');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies then take a year or more to gain the other half of their body weight.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies can sleep 18 to 20 hours a day during that rapid body growth phase.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs sometimes appear to smile with open mouth grinning. This may indicate a relaxed, submissive state.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Tired puppies get cranky similarly to little kids. If you have a fussy puppy, try nap time.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The fastest breed, the Greyhound, can run up to 44 miles per hour.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Perky-eared dogs hear sounds better than floppy-eared dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In general, smaller breeds live longer than larger breeds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('According to a study shared by Cornell University, dogs were domesticated between 9,000 and 34,000 years ago.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Thomas Jefferson helped enact a dog tax in Virginia, because he was annoyed that dogs were killing his sheep.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Stroking dogs and gazing into their eyes releases the "feel good" hormone oxytocin for both people and dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs are omnivores -- they eat meat, grains and vegetables.');
    INSERT INTO "Dogs" ("Fact") VALUES ('More than half of all U.S. presidents have owned dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('President Calvin Coolidge owned at least a dozen dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('At about 6 inches, the Chihuahua is the shortest breed.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Irish Wolfhounds, the tallest breed, are 30 to 35 inches tall.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs who bark the most: Miniature Schnauzers, Cairn Terriers, Yorkshire Terriers, Fox Terriers and West Highland White Terriers.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies have 28 teeth and adult dogs have 42.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The best age to bring a puppy home is 8 to 12 weeks.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can see best at dawn and dusk.');
    INSERT INTO "Dogs" ("Fact") VALUES ('New puppies have heat sensors in their noses to help find their moms while their eyes and ears are closed.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs sense of smell is reduced by up to 40 percent when hes overheated and panting.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Highly trainable dog breeds such as Golden Retrievers, Labrador Retrievers, German Shepherds and Collies are more kid-friendly than some other breeds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Bichons, Portuguese Water Dogs, Kerry Blue Terriers, Maltese and Poodles are all good choices if you have allergies since they shed less than other breeds.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The average number of puppies in a litter is four to six.');
    INSERT INTO "Dogs" ("Fact") VALUES ('There are nearly 14,000 animal shelters and rescue groups across North America.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Service dogs are recognized in the U.S. as "necessary medical equipment".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Therapy dogs, who bring healing to individuals and families by visiting hospitals schools or retirement homes, differ from service dogs, who assist individuals who have disabilities.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have three eyelids, including one to keep their eyes moist and protected.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Chow Chows are born with pink tongues, which turn blue-black at 8 to 10 weeks.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs who have been spayed or neutered live longer than intact dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A bloodhound named Tigger holds the record for the longest ears, each measuring more than 13 inches.');
    INSERT INTO "Dogs" ("Fact") VALUES ('In 1969, Lassie was the first animal inducted into the Animal Hall of Fame.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Alaskan Malamute can withstand temperatures as low as 70 degrees below zero.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Petting a dog can lower your blood pressure.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Stray dogs in Moscow have learned to ride the subway to find food.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Although it was once illegal to keep dogs as pets in Icelands capital city, the laws have been relaxed.');
    INSERT INTO "Dogs" ("Fact") VALUES ('President Lyndon Johnsons beagles were named Him and Her.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Puppies are blind, deaf and toothless when born.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs curl up to keep themselves warm and protect vital organs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Norwegian Lundehund is the only dog with six toes on each foot.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can get jealous when their humans display affection toward someone or something else.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dogs whiskers are used as sensing devices.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Three of the 12 dogs on the Titanic survived.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Your pup reaches his full size between 12 and 24 months.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The U.S. has the highest dog population in the world.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The Berger Picard, Miniature American Shepherd and Lagotto Romagnolo are the newest dog breeds recognized by the American Kennel Club in 2015.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Max, Jake, Maggie and Molly are the most popular dog names.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Walt Disneys family dog -- named Sunnee -- was the inspiration behind "Lady and the Tramp".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Teams of dogs compete for the fastest time without errors in Flyball races.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A German Shepherd named Orient accompanied her blind owner Bill Irwin as he became the first blind person to through-hike the 2,100-mile Appalachian Trail in 1990.');
    INSERT INTO "Dogs" ("Fact") VALUES ('National Geographics Dr. Brady Barr measured a dogs average bite force at 320 pounds of pressure per square inch.');
    INSERT INTO "Dogs" ("Fact") VALUES ('President Theodore Roosevelts Bull Terrier Pete ripped the pants off French Ambassador Jules Jusserand.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Female dogs carry puppies for about nine weeks before birth.');
    INSERT INTO "Dogs" ("Fact") VALUES ('With love and a little patience, dogs can learn to walk backwards, salute and bow.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Pit bulls have been given a bad rap. BADRAP was started in the San Francisco Bay area on behalf of "pit bulls and their people" and was ranked nationally as a No. 1 high-impact nonprofit for animal welfare.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Revolutionary War soldiers sometimes brought their dogs with them into battle.');
    INSERT INTO "Dogs" ("Fact") VALUES ('The American Water Spaniel was the first hunting breed developed to retrieve from boats.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have a ligament in the neck which allows them to conserve energy while running long distances following scent trails with their nose to the ground. Many other species have a similar ligament and it is called a Paddywhack.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs belong to a biological family called the Canidae, a member of this family is called a canid. This is the origin of the adjective "canine" which means "relating to a characteristic of dogs".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs have a very good sense of smell. The part of a dogs brain that analyses smell is 40 times larger than a humans and they can smell 1,000 to 10,000 times better than us.');
    INSERT INTO "Dogs" ("Fact") VALUES ('About one-third of a dogs brain is dedicated to smell.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dog noses are also very cute and easy to boop.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dog could detect a teaspoon of sugar if you added it to an Olympic-sized swimming pool full of water.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Some dogs can tell if a human is about to have an epileptic fit.');
    INSERT INTO "Dogs" ("Fact") VALUES ('About 12 percent of the air that a dog breathes goes into a special area in the back of the nose that is dedicated to smelling.');
    INSERT INTO "Dogs" ("Fact") VALUES ('A dog can both sniff and breathe at the same time.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs know from which nostril a smell has entered.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can use their sense of smell to gauge our emotions, they can smell fear, anxiety, even sadness. This is because they can smell hormones such as adrenaline.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Police dogs can smell human bodies even when they are buried up to 3 meters in the ground.');
    INSERT INTO "Dogs" ("Fact") VALUES ('If you want a dog to see things in a green background the best color is blue.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs cannot distinguish between red and green as these colors would appear as shades of grey to a dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs love to chew bones but cooked bones and bones that can splinter such as cooked chicken bones should not be given to dogs.');
    INSERT INTO "Dogs" ("Fact") VALUES ('When dogs were evolving, bone marrow could sometimes form an important part of their diet.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs often bury bones so that they can dig them up at some moment in the future when they are hungry.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Although dogs have some sweat glands in their feet, their principal way of losing heat when they are too hot is by panting.');
    INSERT INTO "Dogs" ("Fact") VALUES ('When dogs have been doing a lot of exercise, they pant. It is not because they are out of breath. Dogs have developed the method of losing heat by panting because sweating would not be very efficient due to all the fur.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Female dogs can get pregnant when their bodies undergo changes which make them receptive to male dogs. This is called being on heat or in estrus.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Male dogs know the female is in heat due to a smell emitted from the female dog.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Most dogs go in heat every 6 months and estrus lasts between 7 and 18 days.');
    INSERT INTO "Dogs" ("Fact") VALUES ('When dogs copulate, it is very normal for them to get stuck together and it may last for up to 45 minutes.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Most vets recommend that female dogs dont get pregnant until the third estrus.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Pregnancy can be prevented by spaying the female dog, this involves removing both the ovaries and the uterus.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs dont go into menopause and will continue to go on heat indefinitely unless they are spayed.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Male dogs have a bone in their penis.');
    INSERT INTO "Dogs" ("Fact") VALUES ('It is not possible to know how many puppies a dog will have just by looking. The appearance can be very deceptive.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Corgi is Welsh for "dwarf dog".');
    INSERT INTO "Dogs" ("Fact") VALUES ('Greyhounds can reach a speed of up to 45 miles per hour.');
    INSERT INTO "Dogs" ("Fact") VALUES ('Dogs can discriminate the emotional expressions of human faces.');
END $$;

COMMIT;
